[PKG-2951] extension unavailable rust tokenizer
AnacondaRecipes/json-stream-rs-tokenizer-feedstock pull request #2
Opened 2023-09-28 16:24 UTC by lorepirri

[PKG-2951] extension unavailable rust tokenizer

2023-10-02 15:38 UTC, cbouss requested changes

2023-10-02 15:38 UTC, cbouss commented on recipe/meta.yaml
>      - python
`- setuptools-rust 1.5.2` --> `- setuptools-rust >=1,<2`
(This helps with rebuilds)

2023-10-02 15:38 UTC, cbouss commented on recipe/meta.yaml
> +    - pip install "json-stream-rs-tokenizer[test]"
This pip install will not be stable over time, and might even get you json-stream-rs-tokenizer from pypa.
If you need test dependencies, add them to` test/requires`. Perhaps we can do without running the benchmark..

2023-10-02 15:44 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pip install "json-stream-rs-tokenizer[test]"
Could we use native conda packages?

2023-10-02 15:44 UTC, JeanChristopheMorinPerso commented on recipe/run_test.py
Is this file executed?

2023-10-02 16:12 UTC, lorepirri commented on recipe/run_test.py
it is ([implicit](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#run-test-script)):

```
                   INFO   ===== testing package: json-stream-rs-tokenizer-0.4.22-py38h15d1925_1 =====                                               
                   INFO   running run_test.py                                                                                                       
                   INFO   import: 'json_stream_rs_tokenizer'                                                                                        
                   INFO   json_stream_rs_tokenizer.rust_tokenizer_or_raise()                                                                        
```

https://cloud.prefect.io/anaconda/flow-run/15794fc0-0259-43d2-9613-f0a62d213fca?logs=&logId=457d5fac-0896-4c04-8c7b-16db35b931c3

2023-10-02 16:26 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
> +    - pip install "json-stream-rs-tokenizer[test]"
is not that they want the rust json-stream-rs-tokenizer running out of the box in user environment ? not just in test, but rather run ?

2023-10-02 17:48 UTC, lorepirri commented on recipe/meta.yaml
> +    - pip install "json-stream-rs-tokenizer[test]"
Yes but `json_stream 2.3.2` is only available on the SF channel

2023-10-02 17:50 UTC, lorepirri commented on recipe/meta.yaml
> +    - pip install "json-stream-rs-tokenizer[test]"
I use `requires` but `json_stream 2.3.2` is only available on the SF channel. I will add the `channel` in the `abs.yaml`.

2023-10-02 17:50 UTC, lorepirri commented on recipe/meta.yaml
>      - python
thanks

2023-10-02 18:17 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - rm tests/test_via_benchmark.py   # [not win]
You can just skip the test using `pytest -k 'not test_via_benchmark'`

2023-10-02 19:19 UTC, lorepirri commented on recipe/meta.yaml
> +    - rm tests/test_via_benchmark.py   # [not win]
ok

2023-10-02 19:21 UTC, lorepirri commented on abs.yaml
> +- sfe1ed40
to source `json_stream 2.3.2` from SF channel

2023-10-02 19:28 UTC, lorepirri commented on recipe/meta.yaml
> +    - rm tests/test_via_benchmark.py   # [not win]
it tries to import the module even when the test inside the module is skipped

https://cloud.prefect.io/anaconda/flow-run/0cfc0ac9-ad03-4ad1-8594-eb90b01eebd5?logs=&logId=abe6a0d1-94ce-4f6b-b62e-cf15054224f0

I revert for now

2023-10-02 19:34 UTC, lorepirri commented on recipe/meta.yaml
> +    - rm tests/test_via_benchmark.py   # [not win]
I used `--ignore`, it will ignore the whole py file

2023-10-02 20:56 UTC, M-Waszkiewicz-Anaconda reviewed
unnecessary conftest.py, otherwise LGTM

2023-10-02 20:56 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
> +  - url: https://raw.githubusercontent.com/smheidrich/py-json-stream-rs-tokenizer/v0.4.22/tests/conftest.py
there is https://github.com/smheidrich/py-json-stream-rs-tokenizer/blob/v0.4.23/tests/conftest.py ?

2023-10-02 22:35 UTC, lorepirri commented on recipe/meta.yaml
> +  - url: https://raw.githubusercontent.com/smheidrich/py-json-stream-rs-tokenizer/v0.4.22/tests/conftest.py
yes, `conftest.py` is present in the source repository, but not in the tarball. That's why I source it directly from the source repository (and we should do it also for also for `0.4.23`).

The `conftest.py` is needed for the tests because some of them use the fixture `to_bytes_or_str_buf`.

**0.4.22**

https://pypi.io/packages/source/j/json-stream-rs-tokenizer/json-stream-rs-tokenizer-0.4.22.tar.gz

https://pypi.org/project/json-stream-rs-tokenizer/0.4.22/#files

https://pypi.io/packages/source/j/json-stream-rs-tokenizer/json-stream-rs-tokenizer-0.4.22.tar.gz

https://files.pythonhosted.org/packages/39/5c/f74ef342ff8feabcd1485fca51b08308f01c11b99016f2895cfb8fdaee4e/json-stream-rs-tokenizer-0.4.22.tar.gz


**0.4.23**

https://pypi.org/project/json-stream-rs-tokenizer/0.4.23/#files

https://pypi.io/packages/source/j/json-stream-rs-tokenizer/json-stream-rs-tokenizer-0.4.23.tar.gz

https://files.pythonhosted.org/packages/b9/91/dc4774ea9bde220a25ed81409ffa41c78cab6c88e825ba5506b85bf5c24a/json-stream-rs-tokenizer-0.4.23.tar.gz

2023-10-02 22:36 UTC, lorepirri commented
> unnecessary conftest.py, otherwise LGTM

The `conftest.py` is needed for the tests because some of them use the fixture `to_bytes_or_str_buf`, and it's not present in the tarball

2023-10-03 04:16 UTC, varlackc approved these changes
Looks Good

2023-10-03 08:16 UTC, skupr-anaconda approved these changes
LGTM but small fixes

2023-10-03 08:16 UTC, skupr-anaconda commented on abs.yaml
> +channels:
`upload_channels` instead?

2023-10-03 08:16 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  - url: https://raw.githubusercontent.com/smheidrich/py-json-stream-rs-tokenizer/v0.4.22/tests/conftest.py
```suggestion
  - url: https://raw.githubusercontent.com/smheidrich/py-{{ name }}/v{{ version }}/tests/conftest.py
```

2023-10-03 10:44 UTC, lorepirri commented on abs.yaml
> +channels:
the package is for `defaults`, not SF

2023-10-03 10:53 UTC, skupr-anaconda commented on abs.yaml
> +channels:
Ah, it's only for testing the package. Good to know because I haven't tested packages yet in that way

2023-10-03 11:00 UTC, lorepirri commented on abs.yaml
> +channels:
Tests depend on `json_stream 2.3.2` which is only on SF. In this way prefect is able to source the dependency from the SF channel.

The `channels` _should_, in my understanding, not be used to upload to channels unless the `upload_without_merge` flag is set to `true`.

In case, I should remove this. I am not sure though if the build will succeed on Prefect after merging.

2023-10-03 11:01 UTC, lorepirri commented on abs.yaml
> +- sfe1ed40
see above comment https://github.com/AnacondaRecipes/json-stream-rs-tokenizer-feedstock/pull/2/files#r1343917103

2023-10-03 11:03 UTC, skupr-anaconda commented on abs.yaml
> +- sfe1ed40
I don't see `json_stream 2.3.2 in` the test environment. I think you should move it from `test/requires` to `test/downstreams` for testing it. Because `json_stream` relies on `json-stream-rs-tokenizer`  https://github.com/AnacondaRecipes/json_stream-feedstock/blob/main/recipe/meta.yaml

2023-10-03 11:04 UTC, lorepirri commented on recipe/meta.yaml
> +  # check again for the next versions and eventually remove this (needed for upstream tests)
```suggestion
  # check again for the next versions and eventually remove this (needed for upstream tests)
  # Check this PR: https://github.com/smheidrich/py-json-stream-rs-tokenizer/pull/95
```

2023-10-03 11:05 UTC, skupr-anaconda commented on abs.yaml
> +channels:
Looks like it's a cyclic dependency as it's needed for testing the package itself and at the same time it's a downstream package

2023-10-03 11:08 UTC, skupr-anaconda commented on abs.yaml
> +channels:
I would ignore tests that require `json_stream 2.3.2` and remove it from `test/requires` + abs.yaml (`channels`)

2023-10-03 11:10 UTC, lorepirri commented on abs.yaml
> +channels:
ok, got it

2023-10-03 11:21 UTC, lorepirri commented on abs.yaml
> +- sfe1ed40
see https://github.com/AnacondaRecipes/json-stream-rs-tokenizer-feedstock/pull/2#discussion_r1343917103

2023-10-03 11:21 UTC, lorepirri commented on abs.yaml
> +channels:
done

2023-10-03 12:39 UTC, lorepirri commented on recipe/run_test.py
I [made rust_tokenizer_or_raise test inline](https://github.com/AnacondaRecipes/json-stream-rs-tokenizer-feedstock/pull/2/commits/c31996f4d1d9ed836fb7f1184a620e3329f0922c) within the recipe. Explicit.

2023-10-03 13:03 UTC, JeanChristopheMorinPerso approved these changes

2023-10-03 13:11 UTC, cbouss approved these changes

2023-10-03 13:46 UTC, M-Waszkiewicz-Anaconda approved these changes
LGTM

2023-10-03 17:46 UTC, merged